name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby 3.2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.5'
        bundler-cache: true  # Cache gems automatically
    
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
         
    - name: Remove containerd package
      run: sudo apt-get remove -y containerd

    - name: Install Docker and containerd.io
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "
          apt-get update && \
          apt-get install -y python3 python3-venv && \
          python3 -m venv /srv/jekyll/venv && \
          source /srv/jekyll/venv/bin/activate && \
          pip install --upgrade pip && \
          if [ -f /srv/jekyll/requirements.txt ]; then pip install -r /srv/jekyll/requirements.txt; fi && \
          chmod -R 777 /srv/jekyll && \
          jekyll build --future --trace"
