name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby 3.2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.5'
        bundler-cache: true  # Cache gems automatically
    
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
