name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby 3.2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.5'
        bundler-cache: true  # Cache gems automatically
    
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install virtualenv
      run: python -m pip install virtualenv  # Install virtualenv if it's missing

    # Create the Python virtual environment
    - name: Create Python virtual environment
      run: |
        python -m venv ~/venv
        sleep 5  # Add a short delay to ensure the environment is fully created
        ls ~/venv/  # Debug: Check if venv directory is created
        source venv/bin/activate
        python -m pip install --upgrade pip  # Upgrade pip to avoid any issues
        pip install -r ./requirements.txt
         
    - name: Remove containerd package
      run: sudo apt-get remove -y containerd

    - name: Install Docker and containerd.io
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future --trace"
